version: '1.0'

services:
  backend:
    container_name: backend
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run start:dev
    env_file:
      - .development.env
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
