version: '3.3'

services:
  backend:
    container_name: backend
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    command: >
      bash -c "npm run build && npm run seed && npm run start:dev"

    env_file:
      - .development.env
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 3002:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
